version: '3'
services:
  db:
    image: 'postgres:12.2-alpine'
    volumes:
      - 'communitytech-tsp-psql:/var/lib/postgresql/data'
    env_file: '.env'
    ports:
      - '5432:5432'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/communitytech-tsp
    env_file: '.env'
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  communitytech-tsp-psql:
